### ISSUE TITLE
Error in rule rename_MEGAMATRIX

### ISSUE THREAD

**Issue by Redmattski** [Carrion-lab/bacLIFE#8]
Running this on Arch Linux and this is failing in the rule rename_MEGAMATRIX phase.  I have not been able to identify what is driving this.  

Any help appreciated, log file attached

[2024-04-28T215049.881236.snakemake.log](https://github.com/Carrion-lab/bacLIFE/files/15143532/2024-04-28T215049.881236.snakemake.log)

**Comment by gguerr001** [comment]
Probably the error you got has to be with some missmatch in the names of the genomes. The column names in the file MEGAMATRIX.txt should be the same as in the bacLIFE_name column in the names_equivalence.txt file. 
You can try to manually run the code src/rename_MEGAMATRIX.R in Rstudio to see where exactly is the error (can't see any specific error in the snakemake log). 
To do this you can replace the arguments in the script as follow:

- args[1] --> "MEGAMATRIX.txt"
- args[2] --> "intermediate_files/BiG-SCAPE/big_scape_binary_table.txt"
- args[3] --> "names_equivalence.txt"
- args[4] --> "MEGAMATRIX_renamed.txt"
- args[5] --> "intermediate_files/BiG-SCAPE/big_scape_binary_table_renamed.txt"
- args[6] --> "mapping_file.txt"

In addition, if you share the "names_equivalence.txt" file I can check if there is any genome name that could be conflictive because of special characters

**Comment by Redmattski** [comment]
Thanks for the pointers - the issue was related to an issue I had introduced to the "names_equivalence.txt".  I am rerunning with a slightly different data scope to avoid the issue and will confirm this is not a problem once the run has completed.

**Comment by Redmattski** [comment]
This is working as expected - thanks
